function [ ProgressBar ] = myWaitBarUpdate( ProgressBar )
%myWaitBarUpdate aktualizacja WaitBara
%   ProgressBar - struktura z niezbêdnymi informacjami

timePast=ProgressBar.timeMEM+toc(ProgressBar.topTimer);%czas który up³yno³ od za³¹czenia g³ównego timera
ProgressBar.timeLeft=ProgressBar.allTime-timePast;%przewidywany czas do koñca

waitbar(...
    timePast/ProgressBar.allTime,...
    ProgressBar.wb,...
    sprintf('Progress: %.2f%% Estimated time left: %.2f s / %.1f s\n%s',...
        timePast/ProgressBar.allTime*100,...
        ProgressBar.timeLeft,...
        ProgressBar.allTime,...
        ProgressBar.extraMsg));

end

